### ISSUE TITLE
license checker error

### ISSUE THREAD

**Issue by msekkappan** [NationalSecurityAgency/skills-client-examples#25]
Transpiling (Yarn Build) react code throws this error, can you point me to fixing.

C:\Projects\Skills client examples\react-example>yarn build
yarn run v1.22.17
$ npm run licenseDepCheck && npm run licenseHeaderCheck && react-scripts build

> react-example@0.1.0 licenseDepCheck C:\Projects\Skills client examples\react-example
> license-checker --production --onlyAllow='MIT;ISC;Apache-2.0' --summary

Package "react-example@0.1.0" is licensed under "Apache-2.0" which is not permitted by the --onlyAllow flag. Exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-example@0.1.0 licenseDepCheck: `license-checker --production --onlyAllow='MIT;ISC;Apache-2.0' --summary`
npm ERR! Exit status 1

Thank you
Malathi

**Comment by sudo-may** [comment]
@msekkappan thanks for reporting; we here at SkillTree use ``npm`` for development and within CI which seems to work fine:
```
$ git clone git@github.com:NationalSecurityAgency/skills-client-examples.git
$ skills-client-examples/react-example/
$ npm install
$ npm run build
...
Command succeeded
Creating an optimized production build...
Compiled successfully.
```
Were you following the [SkillTree Quick Start](https://skilltreeplatform.dev/dashboard/install-guide/quickStart.html)? Usually there is no need to build a JS artifact from ``skills-client-examples``. For example, if you are looking to integrate SkillTree into a webapp there are SkillTree libraries already available in the npm repository ([Integration Guide](https://skilltreeplatform.dev/skills-client/))

Hope this helps but please don't hesitate to share your use-case with. Have a great day!

**Comment by msekkappan** [comment]
Thank you for your reply.  
1. I got it compiled after removing --onlyAllow='MIT;ISC;Apache-2.0' in the package.json.
2. I was following the readme under skills-client-examples/react-example/ which uses yarn
