### ISSUE TITLE
Read only user?

### ISSUE THREAD

**Issue by msekkappan** [NationalSecurityAgency/skills-client-examples#28]
Is it possible to create a read only user for all projects/some projects/project?  The potential use case is to setup the display under this user, we like to see all projects data in the dashboard.

**Comment by rmmayo** [comment]
hi @msekkappan, thanks for reaching out!

I'm not sure I fully understand your use case, but let me give you some options and see if that helps.

To start, we do not currently support the ability for a user that is not a project admin to be able to navigate the admin views of a project but NOT create or update items.  We do however have a ticket and plan to support this functionality in the future.  Please see NationalSecurityAgency/skills-service#526

With that said, we do allow standard users to view their "Skills Display" of project(s) in the dashboard via the "Progress and Ranking" pages, which allows a user to drill-down into a specific project and see their progress in different subjects, skills, badges, etc. as well as their rank compared to other users.

The Progress and Ranking Views are disabled by default, but can be easily enabled by setting the following configuration properties: 
```
# enable Progress and Ranking Views
skills.config.ui.rankingAndProgressViewsEnabled=true

# optionally change default for the landing page (admin is the default)
skills.config.ui.defaultLandingPage=progress
```
In order for a user to view a project from Progress and Rankings, the admin of the project must first enable `Production Mode` on the project's Settings page, and then the user will need to add the project to their "My Projects" list.  These steps as well as the configuration options are further documented [here](https://skilltreeplatform.dev/dashboard/user-guide/progress-and-ranking.html).

Additionally, this same Skills Display component and be easily integrated into your web-based application by utilizing the SkillTree client libraries.  The steps for this are documented [here](https://skilltreeplatform.dev/skills-client/#skills-display-integration).  

Also, all the [SkillTree docs](https://skilltreeplatform.dev/) including the dashboard and integration guide can be found here: 

- https://skilltreeplatform.dev/dashboard/user-guide/
- https://skilltreeplatform.dev/skills-client/

I hope this helps!  Please let us know if you have any other questions!

**Comment by msekkappan** [comment]
Perfect, this works
