### ISSUE TITLE
Display all projects/skills

### ISSUE THREAD

**Issue by msekkappan** [NationalSecurityAgency/skills-client-examples#33]
Specifying     
window.SkillsClient.SkillsConfiguration.configure({
      serviceUrl: 'http://localhost:8080',
      projectId: 'VeryCoolProject',
      authenticator: 'gitlab',
    });

brings back skills within the project.  Is it possible to bring all projects that the user has reported.

Thanks

**Comment by sudo-may** [comment]
@msekkappan  The Skills Display embedded component represents a single project - a single integrated web-application. Usually a single web-application is represented by a single SkillTree project. There isn't currently an embedded component that visualizes users' progress/ranking across multiple projects. With that said, the SkillTree dashboard does have [The Progress and Ranking pages](https://skilltreeplatform.dev/dashboard/user-guide/progress-and-ranking.html) which do visualize the user's current Progress and Ranking across multiple projects.

Hope this helps but if not, if you can please elaborate further about the use-case we can hopefully point you in the right direction.
